# Generated by Django 5.0.6 on 2024-07-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hangman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('attempts', models.IntegerField()),
                ('guessed_letters', models.CharField(max_length=50)),
                ('game_over', models.BooleanField()),
                ('game_won', models.BooleanField()),
                ('game_lost', models.BooleanField()),
            ],
        ),
    ]
